In [10]:
import numpy as np
a=[[2,3,5],[5,7,8]]
a=np.array(a)
b=[[1,2],[3,10],[2,6]]
b=np.array(b)
print(np.matmul(a,b))

[[ 21  64]
 [ 42 128]]


In [17]:
ma=[[32,57,89,82,98,57,88,56,93,91],
    [88,93,20,70,56,83,92,100,80,97],
    [82,75,83,95,96,90,77,82,90,88]]
print(np.max(ma,axis=1))
print(np.sum(ma,axis=1))

[ 98 100  96]
[743 779 858]
